### ISSUE TITLE
Problem of output the list of steps

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_AutogridLoading#1]
It seems that there is a repeating when recording of the steps 
![image](https://user-images.githubusercontent.com/52638056/144326771-9f10ab31-31f8-4046-a812-a3f091bcd209.png)
 And then I try to finish all the steps according to the correct answer but I still could not get 100 score. Maybe this is the reason why I cannot get full score?

**Comment by Wandayu** [comment]
This is due to a nasty bug inside Unreal where begin play is executed multiple times in level blueprint, which will be fixed in the next release.
