### ISSUE TITLE
The position to pour the liquid nitrogen

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_AutogridLoading#4]
There is no clear indication on which position to pour the liquid nitrogen, the indication of the arrow is not clear
![image](https://user-images.githubusercontent.com/52638056/115342162-cef0cd80-a177-11eb-985e-690db2d4892e.png)

**Comment by SchubyDong** [comment]
I have adjusted the position of the arrow to make it more clear.
