### ISSUE TITLE
Could not continue after I pour the liquid nitrogen for 5 mins

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_AutogridLoading#5]
![image](https://user-images.githubusercontent.com/52638056/115342305-0e1f1e80-a178-11eb-9e0c-62346b063e39.png)
After I pour the LN for 5 mins in this position, there is no response, unless I put the LN dewar into the workstation, it can go to the next step,

**Comment by SchubyDong** [comment]
In this game, we are supposed to pour LN into the center part of the station. If the side entry can also work, I can add an interaction area for it.
